version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: satisfactory_calculator
    volumes:
      - ./web/:/usr/src/web
      - ./docs/:/usr/src/web/build
    ports:
      - 3333:3000
    tty: true

